In [2]:
import tensorflow as tf
import numpy as np

Numpy and tf.Tensor are interconvertible. The simplest way to define a tf.Tensor is to use the `tf.constant` function.

In [2]:
x = tf.constant([
    [1.1, 1.2, 1.3],
    [2.1, 2.2, 2.3],
    [2.4, 2.5, 2.6]
], dtype=tf.float32)
x

<tf.Tensor: id=0, shape=(3, 3), dtype=float32, numpy=
array([[1.1, 1.2, 1.3],
       [2.1, 2.2, 2.3],
       [2.4, 2.5, 2.6]], dtype=float32)>

In [3]:
y = np.array([
    [10.],
    [20.],
    [30.]
])
yt = tf.constant(y, dtype=tf.float32)
yt

<tf.Tensor: id=2, shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [30.]], dtype=float32)>

Tensors have a bunch of convenience functions, including for doing linear algebra like `tf.matmul`, `tf.add`, etc.

In [4]:
z = tf.matmul(x, yt)
z

<tf.Tensor: id=4, shape=(3, 1), dtype=float32, numpy=
array([[ 74.],
       [134.],
       [152.]], dtype=float32)>

Tensors support the same slicing ops that numpy ndarrays support.

In [5]:
a = np.arange(10)
at = tf.constant(a)
at

<tf.Tensor: id=6, shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
at[2:5]

<tf.Tensor: id=11, shape=(3,), dtype=int64, numpy=array([2, 3, 4])>

In [7]:
at[at>=5]

W0812 20:58:01.272425 4589360576 deprecation.py:323] From /Users/avilay/venvs/ai/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1340: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


<tf.Tensor: id=41, shape=(5,), dtype=int64, numpy=array([5, 6, 7, 8, 9])>

When creating a tf.Tensor from a numpy ndarray, the values are effectively copied. Thereafter, we can change the ndarray values, but the tf.Tensor will remain unchanged. Moreover, the tf.Tensor is completely immutable.

In [8]:
a[2] = 200
a[2:5]

array([200,   3,   4])

In [9]:
at[2:5]

<tf.Tensor: id=46, shape=(3,), dtype=int64, numpy=array([2, 3, 4])>

In [10]:
at[2] = 500

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Reshaping a tf.Tensor is the same as reshaping a numpy ndarray.

In [11]:
bt = tf.reshape(at, (5, 2))
bt

<tf.Tensor: id=49, shape=(5, 2), dtype=int64, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])>

In [12]:
at

<tf.Tensor: id=6, shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

Another class of tensors are `Variables`. These are mutable and are ready to have graidents calculated on them.

In [13]:
x = tf.Variable(tf.ones(3))
x

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [14]:
x[0].assign(100.)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([100.,   1.,   1.], dtype=float32)>

In [15]:
x

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([100.,   1.,   1.], dtype=float32)>

In [16]:
at[0].assign(100.)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [3]:
x = tf.constant([1., 2., 3.])

In [4]:
len(x)

3