In [1]:
import os.path as path
import numpy as np
import tensorflow as tf

In [2]:
np.set_printoptions(precision=3)

# 2D Convolutions
https://towardsdatascience.com/a-comprehensive-introduction-to-different-types-of-convolutions-in-deep-learning-669281e58215

### Single Channel

In [3]:
red_filter = np.array([
    [1., 0., -1.],
    [1., 0., -1.],
    [1., 0., -1.]
])
red_filter_full = tf.constant(red_filter.reshape(3, 3, 1, 1))

In [4]:
red = np.array([
    [10., 10., 10., 0., 0., 0.],
    [10., 10., 10., 0., 0., 0.],
    [10., 10., 10., 0., 0., 0.],
    [10., 10., 10., 0., 0., 0.],
    [10., 10., 10., 0., 0., 0.],
    [10., 10., 10., 0., 0., 0.]
])
red_batch_of_one = tf.constant(red.reshape((1, 6, 6, 1)))

In [5]:
red_out = tf.nn.conv2d(red_batch_of_one, red_filter_full, strides=1, padding="VALID")
print(red_out.shape)
red_out[0, :, :, 0]

(1, 4, 4, 1)


<tf.Tensor: id=6, shape=(4, 4), dtype=float64, numpy=
array([[ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.]])>

In [6]:
green_filter = np.array([
    [2., 0., -2.],
    [2., 0., -2.],
    [2., 0., -2.]
])
green_filter_full = tf.constant(green_filter.reshape(3, 3, 1, 1))

In [7]:
green = np.array([
    [30., 30., 30., 0., 0., 0.],
    [30., 30., 30., 0., 0., 0.],
    [30., 30., 30., 0., 0., 0.],
    [30., 30., 30., 0., 0., 0.],
    [30., 30., 30., 0., 0., 0.],
    [30., 30., 30., 0., 0., 0.]
])
green_batch_of_one = tf.constant(green.reshape((1, 6, 6, 1)))

In [8]:
green_out = tf.nn.conv2d(green_batch_of_one, green_filter_full, strides=1, padding="VALID")
print(green_out.shape)
green_out[0, :, :, 0]

(1, 4, 4, 1)


<tf.Tensor: id=13, shape=(4, 4), dtype=float64, numpy=
array([[  0., 180., 180.,   0.],
       [  0., 180., 180.,   0.],
       [  0., 180., 180.,   0.],
       [  0., 180., 180.,   0.]])>

In [9]:
blue_filter = np.array([
    [0.5, 0., -0.5],
    [0.5, 0., -0.5],
    [0.5, 0., -0.5]
])
blue_filter_full = tf.constant(blue_filter.reshape(3, 3, 1, 1))

In [10]:
blue = np.array([
    [20., 20., 20., 0., 0., 0.],
    [20., 20., 20., 0., 0., 0.],
    [20., 20., 20., 0., 0., 0.],
    [20., 20., 20., 0., 0., 0.],
    [20., 20., 20., 0., 0., 0.],
    [20., 20., 20., 0., 0., 0.]
])
blue_batch_of_one = tf.constant(blue.reshape((1, 6, 6, 1)))

In [11]:
blue_out = tf.nn.conv2d(blue_batch_of_one, blue_filter_full, strides=1, padding="VALID")
print(blue_out.shape)
blue_out[0, :, :, 0]

(1, 4, 4, 1)


<tf.Tensor: id=20, shape=(4, 4), dtype=float64, numpy=
array([[ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.]])>

### Multi-Channel

In [12]:
img_filter = np.moveaxis(np.stack([red_filter, green_filter, blue_filter]), 0, 2)
img_filter_full = tf.constant(np.expand_dims(img_filter, axis=3))
print(img_filter_full.shape)
img_filter_full[:, :, 0, 0]

(3, 3, 3, 1)


<tf.Tensor: id=25, shape=(3, 3), dtype=float64, numpy=
array([[ 1.,  0., -1.],
       [ 1.,  0., -1.],
       [ 1.,  0., -1.]])>

In [13]:
img = np.moveaxis(np.stack([red, green, blue]), 0, 2)
img_batch_of_one = tf.constant(np.expand_dims(img, axis=0))
print(img_batch_of_one.shape)
img_batch_of_one[0, :, :, 1]

(1, 6, 6, 3)


<tf.Tensor: id=30, shape=(6, 6), dtype=float64, numpy=
array([[30., 30., 30.,  0.,  0.,  0.],
       [30., 30., 30.,  0.,  0.,  0.],
       [30., 30., 30.,  0.,  0.,  0.],
       [30., 30., 30.,  0.,  0.,  0.],
       [30., 30., 30.,  0.,  0.,  0.],
       [30., 30., 30.,  0.,  0.,  0.]])>

In [14]:
img_out = tf.nn.conv2d(img_batch_of_one, img_filter_full, strides=1, padding="VALID")
img_out.shape
img_out[0, :, :, 0]

<tf.Tensor: id=35, shape=(4, 4), dtype=float64, numpy=
array([[  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.]])>

In [15]:
np.squeeze(red_out) + np.squeeze(green_out) + np.squeeze(blue_out)

array([[  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.]])

## Separable Convolutions

### Spatially Separable

In [22]:
red_filter_v = np.array([1., 1., 1.]).reshape(3, 1)
red_filter_h = np.array([1., 0., -1]).reshape(1, 3)
red_filter_v @ red_filter_h

array([[ 1.,  0., -1.],
       [ 1.,  0., -1.],
       [ 1.,  0., -1.]])

In [24]:
red_filter_v_full = tf.constant(red_filter_v.reshape(3, 1, 1, 1))
red_out_tmp = tf.nn.conv2d(red_batch_of_one, red_filter_v_full, strides=1, padding="VALID")
red_out_tmp.shape

TensorShape([1, 4, 6, 1])

In [25]:
red_filter_h_full = tf.constant(red_filter_h.reshape(1, 3, 1, 1))
red_out = tf.nn.conv2d(red_out_tmp, red_filter_h_full, strides=1, padding="VALID")
red_out.shape

TensorShape([1, 4, 4, 1])

In [26]:
red_out[0, :, :, 0]

<tf.Tensor: id=45, shape=(4, 4), dtype=float64, numpy=
array([[ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.]])>

### Depthwise Separable

In [36]:
tf.stack([tf.squeeze(red_out), tf.squeeze(green_out), tf.squeeze(blue_out)])

<tf.Tensor: id=55, shape=(3, 4, 4), dtype=float64, numpy=
array([[[  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.]],

       [[  0., 180., 180.,   0.],
        [  0., 180., 180.,   0.],
        [  0., 180., 180.,   0.],
        [  0., 180., 180.,   0.]],

       [[  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.],
        [  0.,  30.,  30.,   0.]]])>

In [47]:
tp = np.stack([red_out.numpy().squeeze(), green_out.numpy().squeeze(), blue_out.numpy().squeeze()])
sepout = tf.expand_dims(tf.constant(np.moveaxis(tp, 0, 2)), axis=0)
sepout.shape

TensorShape([1, 4, 4, 3])

In [48]:
sepout[0, :, :, 2]

<tf.Tensor: id=77, shape=(4, 4), dtype=float64, numpy=
array([[ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.],
       [ 0., 30., 30.,  0.]])>

In [55]:
one = np.array([1., 1., 1.]).reshape(1, 1, 3, 1)

In [56]:
one[:, :, 0, 0]

array([[1.]])

In [60]:
img_out_one = tf.nn.conv2d(sepout, one, strides=1, padding="VALID")
img_out_one.shape

TensorShape([1, 4, 4, 1])

In [61]:
img_out_one[0, :, :, 0]

<tf.Tensor: id=87, shape=(4, 4), dtype=float64, numpy=
array([[  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.],
       [  0., 240., 240.,   0.]])>