In [17]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, Conv2DTranspose, Dropout, MaxPooling2D
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
x = tf.constant(np.random.randn(1, 4, 4, 3), dtype=tf.float32)

In [18]:
x.get_shape()[-1].value

3

In [19]:
x = np.random.standard_normal((1, 4, 4, 3))
print(x)
print(x.shape)

[[[[  1.14981806e+00  -2.19824328e-02   3.97108774e-01]
   [  1.27421815e+00   6.34475191e-01  -8.02279874e-01]
   [ -1.31089397e-01   2.48484930e+00  -6.78339869e-01]
   [  6.62854319e-01   8.56493861e-02  -1.26529107e+00]]

  [[  2.11161852e+00   3.53423518e-01  -7.67460832e-02]
   [ -1.15149879e+00  -2.40633694e-01  -9.90615589e-02]
   [  5.51770036e-01  -2.97090646e+00  -2.21209628e+00]
   [  9.97650869e-01  -7.95516710e-01   1.82499145e-01]]

  [[  7.09332684e-01   2.88830274e-03  -1.76811228e+00]
   [  1.81592118e+00  -7.79387021e-01   9.96518161e-02]
   [ -1.87905749e-01  -3.32748180e-01   4.58628818e-01]
   [  4.56961271e-01   4.78668154e-01  -6.60124051e-01]]

  [[  1.72127700e+00  -3.56558830e-02  -4.52425305e-01]
   [  2.17284906e-01   1.42970483e+00   1.65604466e+00]
   [ -1.43014371e+00   2.25946547e-01  -7.24288022e-01]
   [  2.89172230e-01  -9.22578043e-01   3.85409664e-02]]]]
(1, 4, 4, 3)


In [25]:
model = Sequential()
model.add(Conv2DTranspose(filters=3, kernel_size=1, strides=2, input_shape=(4, 4, 3)))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_5 (Conv2DTr (None, 8, 8, 3)           12        
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________
