In [2]:
import gym

In [3]:
env = gym.make("LunarLander-v2")

In [4]:
s = env.observation_space.sample()

In [5]:
type(s)

numpy.ndarray

In [7]:
s.shape

(8,)

In [8]:
s

array([ 1.0970805 ,  0.95585334, -0.25651908, -0.14090632,  1.2149624 ,
        2.0130796 ,  2.278673  , -0.8793368 ], dtype=float32)

In [9]:
a = env.action_space.sample()

In [10]:
type(a)

int

In [11]:
env.action_space

Discrete(4)

In [12]:
a

2

In [13]:
env.action_space

Discrete(4)

In [14]:
def examine(env):
    print("State space: ", env.observation_space, type(env.observation_space))
    print("Action space: ", env.action_space, type(env.action_space))
    s = env.observation_space.sample()
    a = env.action_space.sample()
    print(f"state: {s}\taction: {a}")
    try:
        print("State space dims: ", env.observation_space.n)
        print("Action space dims: ", env.action_space.n)
    except:
        print("Unable to get state/action space dims")

    

In [15]:
env = gym.make("CarRacing-v0")
examine(env)

State space:  Box(96, 96, 3) <class 'gym.spaces.box.Box'>
Action space:  Box(3,) <class 'gym.spaces.box.Box'>
state: [[[237 255 212]
  [162 215 251]
  [198 188 110]
  ...
  [228 161 155]
  [ 54 155  29]
  [138  72  80]]

 [[219 193 168]
  [139  51 165]
  [166  25 209]
  ...
  [100 212 213]
  [  2 246 213]
  [ 37 154 113]]

 [[ 52 121  23]
  [234  63  44]
  [ 95 117 193]
  ...
  [ 57 165 133]
  [217  78 253]
  [ 59 122 252]]

 ...

 [[105  95  90]
  [132  98  53]
  [128  41  85]
  ...
  [ 42 115  67]
  [ 87 179 239]
  [100 210  23]]

 [[ 89  24 224]
  [105 251 121]
  [ 85 228 120]
  ...
  [103 191 100]
  [ 12  19 138]
  [ 98 102 144]]

 [[ 88 196 213]
  [102   7  18]
  [119 237 212]
  ...
  [ 12 208 129]
  [182 124 194]
  [ 64  44  67]]]	action: [0.18002348 0.31887165 0.48050064]
Unable to get state/action space dims


In [16]:
examine(gym.make("BipedalWalker-v2"))

State space:  Box(24,) <class 'gym.spaces.box.Box'>
Action space:  Box(4,) <class 'gym.spaces.box.Box'>
state: [-0.21117371 -0.9824768  -0.59503144  0.40635312 -0.612923   -0.00929004
  0.96289283 -1.5220265   1.4388348   1.0079964   2.1168385   2.0617945
 -0.6870492  -0.54920924  0.04122622 -0.36319357  1.0613993  -0.59297514
  1.6016482  -0.211201   -0.38527086 -0.5777732   0.544194    0.5871252 ]	action: [-0.4605148  -0.36742088  0.05870705  0.3278889 ]
Unable to get state/action space dims


In [17]:
examine(gym.make("Roulette-v0"))

State space:  Discrete(1) <class 'gym.spaces.discrete.Discrete'>
Action space:  Discrete(38) <class 'gym.spaces.discrete.Discrete'>
state: 0	action: 9
State space dims:  1
Action space dims:  38


In [18]:
env = gym.make("CarRacing-v0")

In [19]:
state_space = env.observation_space

In [20]:
state_space.shape

(96, 96, 3)

In [21]:
env = gym.make("Roulette-v0")

In [22]:
state_space = env.observation_space

In [23]:
state_space.shape

()

In [24]:
state_space.n

1

In [25]:
tp = [(0, 0.7), (1, 0.1), (2, 0.2)]

In [30]:
a, b = list(zip(*tp))

In [31]:
a

(0, 1, 2)

In [32]:
b

(0.7, 0.1, 0.2)

In [34]:
import numpy as np

In [35]:
np.random.choice(a, p=b)

2

In [36]:
choices = []
for _ in range(1000):
    choices.append(np.random.choice(a, p=b))

In [37]:
from collections import Counter

In [40]:
Counter(choices).most_common()

[(0, 688), (2, 215), (1, 97)]