In [2]:
import torch

## Simple creational functions

In [2]:
x = torch.tensor([
    [1.1, 1.2, 1.3],
    [2.1, 2.2, 2.3],
    [3.1, 3.2, 3.3]
])
x

tensor([[1.1000, 1.2000, 1.3000],
        [2.1000, 2.2000, 2.3000],
        [3.1000, 3.2000, 3.3000]])

In [3]:
x = torch.zeros(3, 2, dtype=torch.long)
print(x)

x = torch.zeros(3, 2, 2)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [4]:
x = torch.ones(3, 2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
# Can only return 1D tensors
x = torch.arange(3, 10, step=2)
x

tensor([3, 5, 7, 9])

In [6]:
# Can only return 1D tensors
x = torch.linspace(1, 100, 5)
x

tensor([  1.0000,  25.7500,  50.5000,  75.2500, 100.0000])

In [7]:
# Can only return 1D tensors
x = torch.logspace(0, 3, 5)
x

tensor([   1.0000,    5.6234,   31.6228,  177.8279, 1000.0000])

In [8]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:
x = torch.empty(3, 2)
x

tensor([[                              0.0000,
                                      -0.0000],
        [                              0.0000,
         -158494878428494822970612514816.0000],
        [                              0.0000,
                                      -0.0000]])

In [10]:
# Notice that the size is not a vararg but rather a tuple
x = torch.full((3, 2), 3.141)
x

tensor([[3.1410, 3.1410],
        [3.1410, 3.1410],
        [3.1410, 3.1410]])

## Copy Shape
Most of the creational functions also have a \_like variant that will take in another tensor as input and the output tensor will have the same size.

In [11]:
x = torch.ones(3, 2)
y = torch.empty_like(x)
y

tensor([[ 0.0000e+00, -0.0000e+00],
        [ 7.0012e-34, -2.0005e+00],
        [ 1.2096e+04,  7.1846e+22]])

## Random sampling

### Bernoulli Distribution

In [12]:
# x is a Bernoulli random var with p = 0.6
x = torch.bernoulli(torch.tensor([0.6]))
print(x)

# x is a vector whose each element is a Bernoulli random var
# with p = 0.6, p = 0.1, and p = 0.5
x = torch.bernoulli(torch.tensor([0.6, 0.1, 0.5]))
print(x)

tensor([0.])
tensor([1., 0., 1.])


### Multinomial Distribution
TODO

### Normal Distribution

In [13]:
# x is a Normal random var with mu = 0 and sigma = 1
x = torch.normal(torch.tensor([0.0]), torch.tensor([1.0]))
print(x)

# x is a 2 element vector whose each element is a Nomral random var
# each with mu = 1.0 and 10.0 and sigma = 20.0 and 3.0
x = torch.normal(torch.tensor([1.0, 10.0]), torch.tensor([20.0, 3.0]))
print(x)

tensor([-0.1415])
tensor([-20.3099,  12.7078])


In [14]:
# x is a Standard Normal var
# Notice that size is again a vararg
x = torch.randn(3)
print(x)

x = torch.randn(3, 2)
print(x)

tensor([ 0.4165,  0.4517, -0.5298])
tensor([[-0.7730,  0.6455],
        [-0.1937,  0.8972],
        [ 0.5274, -0.5598]])


### Uniform Random Distribution

In [15]:
# x is a uniform random var from [0, 1)
x = torch.rand(3)
print(x)

x = torch.rand(3, 2)
print(x)

tensor([0.7030, 0.9506, 0.6843])
tensor([[0.3634, 0.4702],
        [0.4871, 0.9168],
        [0.6610, 0.2250]])


#### Random Integers

In [16]:
# x is a uniform random int from [low, high)
# Notice that here again, size is a tuple instead of a vararg
x = torch.randint(10, 20, (3, 2))
print(x)

x = torch.randint(10, 20, (3,))
print(x)

tensor([[19., 18.],
        [18., 11.],
        [17., 11.]])
tensor([12., 19., 15.])


#### Random Permutation

In [17]:
# A random permutation of 0 to 9
x = torch.randperm(10)
x

tensor([3, 6, 0, 9, 2, 1, 7, 5, 8, 4])

## Getting Values
It is possible to do index slicing similar to numpy to get parts of a tensor as another tensor. But there is no way to get the tensor values as a Python `list`. For that it is best to first convert to numpy and then to `list`. Tensors are fully compatible with Numpy.

!! IMPORTANT !!
APIs for accessing tensors feel like they are returning a copy of the appropriate slice of the tensor, but in reality both the returned tensor/numpy and the original tensor/numpy share the same underlying numeric object.

In [18]:
# Using numpy style indexing will output a new tensor of the appropriate shape and values
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.],
                  [7., 8., 9.]])
# Get the second row
r = x[1, :]
print(type(r), r.size())
print(r)

# Get the second column
c = x[:, 1]
print(type(c), c.size())
print(c)

<class 'torch.Tensor'> torch.Size([3])
tensor([4., 5., 6.])
<class 'torch.Tensor'> torch.Size([3])
tensor([2., 5., 8.])


In [19]:
# Both the resulting and original tensor share the same underlying numerical object
r[0] = 9999
print(x)
print(r)

x[1,0] = 7777
print(x)
print(r)

tensor([[   1.,    2.,    3.],
        [9999.,    5.,    6.],
        [   7.,    8.,    9.]])
tensor([9999.,    5.,    6.])
tensor([[   1.,    2.,    3.],
        [7777.,    5.,    6.],
        [   7.,    8.,    9.]])
tensor([7777.,    5.,    6.])


### Numpy Compat

In [20]:
import numpy as np

In [21]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
xt = torch.from_numpy(x)
print(xt.size())
print(xt)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [22]:
# Both the ndrarray and Tensor objects share the same underlying data
x[0,0] = 999
print(x)
print(xt)

xt[0,0] = 777
print(xt)
print(x)

[[999   2   3]
 [  4   5   6]]
tensor([[999,   2,   3],
        [  4,   5,   6]])
tensor([[777,   2,   3],
        [  4,   5,   6]])
[[777   2   3]
 [  4   5   6]]


In [23]:
xt = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
x = xt.numpy()
print(x.shape)
print(x)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Here too both the ndarray and Tensor object share the same underlying data
xt[0,0] = 999
print(xt)
print(x)

x[0,0] = 777
print(x)
print(xt)

tensor([[999,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])
[[999   2   3]
 [  4   5   6]
 [  7   8   9]]
[[777   2   3]
 [  4   5   6]
 [  7   8   9]]
tensor([[777,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])


In [25]:
# If I have a single value tensor, no need to convert it to a numpy ndarray. I can simply use item()
x = torch.tensor([1., 2., 3.])
v = x[0]
w = v.item()
print(type(v), v.size())
print(v)
print(type(w))
print(w)

# Unlike the other accessors we have seen so far, w is truly detached from the original tensor
# Changing its value does not cause the original tensor's value to change
w = 999
print(x)
print(w)

<class 'torch.Tensor'> torch.Size([])
tensor(1.)
<class 'float'>
1.0
tensor([1., 2., 3.])
999


## Reshaping Tensors
Most commonly use the `view()` method to reshape a tensor. But there are two additional methods `resize_` and `reshape`. It is not clear which method to use when.

!! IMPORTANT !! Again, the same caveat applies - both the original tensor and the resized tensor share teh same underlying data.

In [26]:
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
v = x.view(3, 2)
print(v)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [27]:
v[0, 0] = 9999
print(x)
print(v)

tensor([[9999.,    2.,    3.],
        [   4.,    5.,    6.]])
tensor([[9999.,    2.],
        [   3.,    4.],
        [   5.,    6.]])


In [28]:
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
r = x.reshape(3, 2)
print(r)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [29]:
# Same caveat with reshape as well - the underlying object between the reshaped and original tensor is the same
r[0, 0] = 9999
print(x)
print(r)

tensor([[9999.,    2.,    3.],
        [   4.,    5.,    6.]])
tensor([[9999.,    2.],
        [   3.,    4.],
        [   5.,    6.]])


In [30]:
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

x.resize_(3, 2)
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


## Mutating Tensors
A lot of mutating functions are instance methods on the tensor object that end with an underscore.

In [31]:
x = torch.ones(3)
x.add_(1)
x

tensor([2., 2., 2.])

In [32]:
# When x does not require grad, I can directly mutate its value using fill_
x = torch.ones(3)
print('Before fill', x)
x.fill_(2)
print('After fill', x)

# But if does require grad, then I cannot directly mutate its value
# I have to use the .data attribute to do that
x = torch.ones(3, requires_grad=True)
print('Before fill', x)
try:
    x.fill_(2)
except RuntimeError as re:
    print(re)
    
x.data.fill_(2)
print('After fill', x)

Before fill tensor([1., 1., 1.])
After fill tensor([2., 2., 2.])
Before fill tensor([1., 1., 1.], requires_grad=True)
a leaf Variable that requires grad has been used in an in-place operation.
After fill tensor([2., 2., 2.], requires_grad=True)


In [33]:
from copy import copy

xt = torch.tensor([[1., 2., 3.]])
x = copy(xt.numpy())
y = x.squeeze()
print(xt.size(), x.shape, y.shape)
y[0] = 999
print(xt)
print(x)
print(y)

torch.Size([1, 3]) (1, 3) (3,)
tensor([[1., 2., 3.]])
[[999.   2.   3.]]
[999.   2.   3.]


## Concatenating Tensors

In [17]:
x = torch.tensor([1, 2])
y = torch.tensor([10, 20, 30])
torch.cat((x, y))

tensor([ 1,  2, 10, 20, 30])

In [14]:
x.size()

torch.Size([2])

In [15]:
type(x)

torch.Tensor

In [18]:
arr = []
arr.append(x)
arr.append(y)
arr

[tensor([1, 2]), tensor([10, 20, 30])]

In [19]:
torch.cat(arr)

tensor([ 1,  2, 10, 20, 30])

## Stacking Tensors
Default dimension of stacking tensors is 0, i.e., it will stack rows of tensors on top of each other.

In [3]:
a = torch.Tensor([1.1, 2.2, 3.3])
b = torch.Tensor([10.1, 20.2, 30.3])
torch.stack((a, b))

tensor([[ 1.1000,  2.2000,  3.3000],
        [10.1000, 20.2000, 30.3000]])

In [8]:
a = torch.Tensor([
    [1.1, 2.2, 3.3],
    [1.4, 2.5, 3.6]
])
b = torch.Tensor([
    [10.1, 20.2],
    [10.4, 20.5],
])
torch.stack((a, b))

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 2 in dimension 2 at ../aten/src/TH/generic/THTensor.cpp:612