In [1]:
%load_ext autoreload
%autoreload 2

In [16]:
from pathlib import Path
import numpy as np
import jax
import jax.numpy as jnp
from compare.datagen import make_ndarray
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [3]:
key = jax.random.PRNGKey(0)
rng = np.random.default_rng()

In [4]:
DATAROOT = Path.home() / "mldata" / "binclass"

In [ ]:
stop = 0
while stop < X.shape[0]:
    start = stop
    stop = start + batch_size
    batch_X = X[start:stop]
    batch_y = y[start:stop]
    yield batch_X, batch_y


In [5]:
X = np.arange(1, 31).reshape(10, 3)
y = np.ones(10)
print(X.shape, y.shape)

(10, 3) (10,)


In [6]:
X = jnp.array(X)
y = jnp.array(y)

In [7]:
X[0:3]

Array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [8]:
y[0:3]

Array([1., 1., 1.], dtype=float32)

In [9]:
X_train, X_val, y_train, y_val = make_ndarray(DATAROOT)

In [10]:
print(X_train.shape, y_train.shape)

(800000, 20) (800000,)


In [11]:
X_train = jnp.array(X_train)
y_train = jnp.array(y_train)

In [13]:
X_train[0:3]

Array([[-0.44953594, -1.9214942 , -6.089468  ,  3.3473158 , -5.24122   ,
         3.7459612 ,  2.6150486 ,  0.73949146, -1.4005231 , -5.24122   ,
         1.5797263 , -1.8132315 ,  3.7042341 ,  0.9614506 , -2.3136702 ,
        -4.7427773 ,  0.51865196, -1.8132315 , -1.9214942 ,  1.2350398 ],
       [-1.5633558 , -0.32196954,  0.964168  ,  4.6737247 , -0.12191527,
        -3.9970465 , -2.259754  ,  2.456047  ,  2.97496   , -0.12191527,
        -0.28306752, -2.285343  ,  0.17361565,  2.8682594 ,  1.7324516 ,
         5.0466723 , -4.673894  , -2.285343  , -0.32196954, -2.307624  ],
       [-0.53054166, -0.79369044,  5.601914  ,  0.5784919 ,  1.6127664 ,
        -3.296832  , -3.781885  ,  1.9096175 ,  5.5680695 ,  1.6127664 ,
         0.17951721, -1.143499  ,  0.13785061,  2.2213032 , -0.11271768,
         5.220177  , -1.635499  , -1.143499  , -0.79369044, -0.85730666]],      dtype=float32)

In [14]:
y_train[0:3]

Array([1, 0, 1], dtype=int32)

In [17]:
help(tqdm)

Help on class tqdm in module tqdm.std:

class tqdm(tqdm.utils.Comparable)
 |  tqdm(*_, **__)
 |  
 |  Decorate an iterable object, returning an iterator which acts exactly
 |  like the original iterable, but prints a dynamically updating
 |  progressbar every time a value is requested.
 |  
 |  Method resolution order:
 |      tqdm
 |      tqdm.utils.Comparable
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __bool__(self)
 |  
 |  __contains__(self, item)
 |  
 |  __del__(self)
 |  
 |  __enter__(self)
 |  
 |  __exit__(self, exc_type, exc_value, traceback)
 |  
 |  __hash__(self)
 |      Return hash(self).
 |  
 |  __init__(self, iterable=None, desc=None, total=None, leave=True, file=None, ncols=None, mininterval=0.1, maxinterval=10.0, miniters=None, ascii=None, disable=False, unit='it', unit_scale=False, dynamic_ncols=False, smoothing=0.3, bar_format=None, initial=0, position=None, postfix=None, unit_divisor=1000, write_bytes=None, lock_args=None, nrows=None, colour=

In [19]:
import torch

torch.backends.mps.is_available()

True