In [1]:
import torch as t
import numpy as np

In [2]:
rng = np.random.default_rng()

In [3]:
emb = t.nn.EmbeddingBag(10, 2, mode="sum")
emb.state_dict()

OrderedDict([('weight',
              tensor([[ 0.4616, -0.0201],
                      [-1.1579,  0.0554],
                      [-0.2165, -2.9054],
                      [ 1.9775,  0.0126],
                      [-0.0811,  0.5435],
                      [-0.8036,  0.8157],
                      [-1.2221,  0.6098],
                      [-0.8639, -0.9343],
                      [-0.7221, -0.4959],
                      [-1.7907, -1.2356]]))])

In [4]:
x = t.LongTensor([[0, 1],
                  [8, 9]])
y = t.from_numpy(rng.standard_normal((2, 2))).to(t.float32)

In [5]:
loss_fn = t.nn.MSELoss()
optim = t.optim.SGD(emb.parameters(), lr=0.1)

In [6]:
optim.zero_grad()
y_hat = emb(x)
loss = loss_fn(y_hat, y)
loss.backward()
optim.step()

In [7]:
emb.state_dict()

OrderedDict([('weight',
              tensor([[ 0.4903,  0.0430],
                      [-1.1292,  0.1184],
                      [-0.2165, -2.9054],
                      [ 1.9775,  0.0126],
                      [-0.0811,  0.5435],
                      [-0.8036,  0.8157],
                      [-1.2221,  0.6098],
                      [-0.8639, -0.9343],
                      [-0.6178, -0.3887],
                      [-1.6864, -1.1284]]))])

In [9]:
x = t.LongTensor([[0, 1],
                  [4, 5],
                  [8, 9]])
y_hat = emb(x)
y_hat

tensor([[-0.6389,  0.1614],
        [-0.8847,  1.3592],
        [-2.3042, -1.5171]], grad_fn=<EmbeddingBagBackward>)

In [14]:
x = t.Tensor([
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
]).to(t.float32)

In [12]:
w = emb.state_dict()["weight"]
w

tensor([[ 0.4903,  0.0430],
        [-1.1292,  0.1184],
        [-0.2165, -2.9054],
        [ 1.9775,  0.0126],
        [-0.0811,  0.5435],
        [-0.8036,  0.8157],
        [-1.2221,  0.6098],
        [-0.8639, -0.9343],
        [-0.6178, -0.3887],
        [-1.6864, -1.1284]])

In [15]:
x @ w

tensor([[-0.6389,  0.1614],
        [-0.8847,  1.3592],
        [-2.3042, -1.5171]])