In [1]:
import numpy as np
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd

In [2]:
np.set_printoptions(precision=3, floatmode="maxprec")

In [3]:
def calc_ne(y, y_hat):
    ctr = np.average(y)
    norm = -(ctr * np.log2(ctr) + (1-ctr) * np.log2(1-ctr))
    xent = -np.average(y * np.log2(y_hat) + (1-y) * np.log2(1-y_hat))
    ne = xent / norm
    return ctr, xent, norm, ne

In [4]:
def geny(ctr, n):
    p = int(ctr * n)
    y = np.zeros(n)
    y[:p] = 1
    return y

In [ ]:
n = 10_000
y_hat = np.full(n, fill_value=0.0001)
ctrs = []
xents = []
nes = []
for ctr in [0.09, 0.07, 0.05, 0.03, 0.01]:
    y = geny(ctr, n)
    ctr, xent, norm, ne = calc_ne(y, y_hat)
    ctrs.append(ctr)
    xents.append(xent)
    nes.append(ne)
    print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")
ctrs = np.array(ctrs)
xents = np.array(xents)
nes = np.array(nes)

In [5]:
from numpy.random import default_rng

In [6]:
rng = default_rng()

In [ ]:
(0.9 - 0.5) * rng.random(5) + 0.5

In [7]:
y = geny(0.2, 10)
y

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

Medium Discriminative Power

In [35]:
y_hat = np.zeros(10)
y_hat[:2] = (0.9 - 0.3) * rng.random(2) + 0.3
y_hat[2:] = (0.6 - 0.1) * rng.random(8) + 0.1
y_hat

# array([0.747, 0.58 , 0.367, 0.19 , 0.391, 0.185, 0.354, 0.149, 0.544, 0.297])

array([0.747, 0.58 , 0.367, 0.19 , 0.391, 0.185, 0.354, 0.149, 0.544,
       0.297])

In [38]:
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

CTR: 0.200	Xent: 0.569	Norm: 0.722	NE: 0.788


Good Discriminative Power

In [16]:
y_hat = np.zeros(10)
y_hat[:2] = (0.9 - 0.7) * rng.random(2) + 0.7
y_hat[2:] = (0.4 - 0.1) * rng.random(8) + 0.1
y_hat
# array([0.708, 0.818, 0.246, 0.163, 0.341, 0.245, 0.226, 0.131, 0.164, 0.108])

array([0.708, 0.818, 0.246, 0.163, 0.341, 0.245, 0.226, 0.131, 0.164,
       0.108])

In [17]:
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

CTR: 0.200	Xent: 0.345	Norm: 0.722	NE: 0.478


Bad Discriminative Power

In [18]:
y_hat = np.zeros(10)
y_hat[:2] = (0.4 - 0.1) * rng.random(2) + 0.1
y_hat[2:] = (0.9 - 0.2) * rng.random(8) + 0.2
y_hat

array([0.32 , 0.17 , 0.597, 0.751, 0.404, 0.526, 0.672, 0.455, 0.353,
       0.219])

In [19]:
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

CTR: 0.200	Xent: 1.282	Norm: 0.722	NE: 1.776


In [ ]:
y_hat = np.full(10, fill_value=0.4)
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:

y_hat

In [ ]:
for _ in range(10):
    y_hat = rng.random(10)
    ctr, xent, norm, ne = calc_ne(y, y_hat)
    print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
y

In [ ]:
y_hat[:2] = (0.49 - 0.01) * rng.random(2) + 0.01
y_hat[2:] = (0.9 - 0.5) * rng.random(8) + 0.5
y_hat

In [ ]:
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
y = geny(0.2, 100_000)

In [ ]:
y_hat = np.full(100_000, fill_value=0.2)
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
y_hat[:20_000] = (0.9 - 0.5) * rng.random(20_000) + 0.5
y_hat[20_000:] = (0.45 - 0.1) * rng.random(80_000) + 0.1
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
y_hat[:20_000] = (0.9 - 0.75) * rng.random(20_000) + 0.75
y_hat[20_000:] = (0.35 - 0.01) * rng.random(80_000) + 0.01
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
y_hat[:20_000] = (0.9 - 0.3) * rng.random(20_000) + 0.3
y_hat[20_000:] = (0.4 - 0.1) * rng.random(80_000) + 0.1
ctr, xent, norm, ne = calc_ne(y, y_hat)
print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
xent_slopes = np.abs((xents[1:] - xents[:-1])/xents[:-1])
ne_slopes = np.abs((nes[1:] - nes[:-1])/nes[:-1])

In [ ]:
fig = make_subplots(rows=2, cols=1)
fig.add_scatter(x=ctrs, y=xents, row=1, col=1, name="Cross Entropy", line_color="red")
fig.add_scatter(x=ctrs, y=nes, row=1, col=1, name="Normalized Entropy", line_color="blue")

fig.add_scatter(x=ctrs, y=xent_slopes, row=2, col=1, name="Cross Entropy Slope", line_color="red")
fig.add_scatter(x=ctrs, y=ne_slopes, row=2, col=1, name="Normalized Entropy Slope", line_color="blue")

In [ ]:
n = 10_000
y_hat = np.full(n, fill_value=0.9999)
ctrs = []
xents = []
nes = []
for ctr in [0.9, 0.93, 0.95, 0.98, 0.99]:
    y = geny(ctr, n)
    ctr, xent, norm, ne = calc_ne(y, y_hat)
    ctrs.append(ctr)
    xents.append(xent)
    nes.append(ne)
    print(f"CTR: {ctr:.3f}\tXent: {xent:.3f}\tNorm: {norm:.3f}\tNE: {ne:.3f}")

In [ ]:
fig = go.Figure(layout_title_text="NE", layout_width=500, layout_height=500)
fig.add_scatter(x=ctrs, y=nes, name="NE")
fig.add_scatter(x=ctrs, y=xents, name="XEnt")

In [ ]:
xents = np.array(xents)

In [ ]:
xent_slopes = (xents[1:] - xents[:-1])/xents[:-1]
xent_slopes = np.abs(xent_slopes)

In [ ]:
nes = np.array(nes)

In [ ]:
ne_slopes = (nes[1:] - nes[:-1])/nes[:-1]
ne_slopes = np.abs(ne_slopes)

In [ ]:
fig = go.Figure(layout_title_text="Slopes", layout_width=500, layout_height=500)
fig.add_scatter(x=ctrs, y=ne_slopes, name="NE Slope")
fig.add_scatter(x=ctrs, y=xent_slopes, name="XEnt Slope")

In [ ]:
y = geny(0.1, 10_000)

In [ ]:
np.sum(y)

In [ ]:
y_hat = np.empty(10_000)

In [ ]:
y_hat[:1000] = np.random.rand(1000) * (0.95 - 0.8) + 0.8

In [ ]:
y_hat[1000:] = np.random.rand(9000) * (0.25 - 0.01) + 0.01

In [ ]:
ff.create_distplot([y_hat[:1000], y_hat[1000:]], ["Positive", "Negative"])

In [ ]:
dataset = np.concatenate((y, y_hat), axis=1)
dataset.shape

In [ ]:
dataset = np.zeros((100, 2))
dataset[:10, 0] = 1
dataset[:10, 1] = np.random.rand(10) * (0.9 - 0.7) + 0.7
dataset[10:, 1] = np.random.rand(90) * (0.3 - 0.1) + 0.1

In [ ]:
df = pd.DataFrame(dataset, columns=["target", "label"])

In [ ]:
px.histogram(df, x="label", color="target", hover_data=df.columns)

In [ ]:
df["label"] = np.full(100, fill_value=0.9)

In [ ]:
import torch as t

In [ ]:
loss_fn = t.nn.BCELoss(reduction='mean')

In [ ]:
y_hat = t.tensor(y_hat)
y = t.tensor(y)

In [ ]:
loss_fn(y_hat, y)

In [ ]:
y_hat = np.empty(10_000)

In [ ]:
y_hat[:1000] = np.random.rand(1000) * (0.7 - 0.45) + 0.45

In [ ]:
y_hat[1000:] = np.random.rand(9000) * (0.45 - 0.2) + 0.2

In [ ]:
y_hat = t.tensor(y_hat)

In [ ]:
loss_fn(y_hat, y)

In [ ]:
fig = px.histogram(x=y_hat.numpy())
fig