In [14]:
import numpy as np
from PIL import Image

In [10]:
class Sphere:
    def __init__(
        self, 
        center, 
        radius, 
        surface_color, 
        reflection=0., 
        transparency=0., 
        emission_color=np.array([0., 0., 0.])
    ):
        self.center = center
        self.radius = radius
        self.surface_color = surface_color
        self.reflection = reflection
        self.transparency = transparency
        self.emission_color = emission_color
        
    def __repr__(self):
        return f"<Sphere(center={self.center} radius={self.radius} surface_color={self.surface_color} reflection={self.reflection} transparency={self.transparency} emission_color={self.emission_color})>"
        
    def intersect(self, ray_orig, ray_dir):
        return 0.5, 0.5

In [12]:
s1 = Sphere(
    center=np.array([0, 0, 0]),
    radius=1.0,
    surface_color=np.array([128, 128, 128]),
    reflection=0.5,
    transparency=0.8,
    emission_color=np.array([200, 120, 100])
)
s1

<Sphere(center=[0 0 0] radius=1.0 surface_color=[128 128 128] reflection=0.5 transparency=0.8 emission_color=[200 120 100])>

In [57]:
s2 = Sphere(np.array([1, 1, 1]), 1.0, np.array([0.2, 0.2, 0.2]))
s2

<Sphere(center=[1 1 1] radius=1.0 surface_color=[0.2 0.2 0.2] reflection=0.0 transparency=0.0 emission_color=[0. 0. 0.])>

In [8]:
ray_orig = np.array([2, 3, 4])
ray_dir = np.array([-1, -2, 3])
s1.intersect(ray_orig, ray_dir)

(0.5, 0.5)

In [ ]:
Sphere(
    center=Vec3f( 0.0, -10004, -20), 
    radius=10000, 
    surface_color=Vec3f(0.20, 0.20, 0.20), 
    reflection=0, 
    transparency=0.0)

In [17]:
np.tan(np.pi/4)

0.9999999999999999

In [20]:
def trace(ray_origin, ray_direction, spheres, depth):
    return np.array([1., 0., 0.])

In [22]:
x = np.array([
    [1, 2, 3],
    [10, 20, 30],
    [100, 200, 300],
    [1000, 2000, 3000]
])

In [23]:
x.shape

(4, 3)

In [29]:
for row in range(4):
    for col in range(3):
        print(x[row, col])

1
2
3
10
20
30
100
200
300
1000
2000
3000


In [25]:
x[0, 0]

1

In [28]:
x[3, 2]

3000

In [30]:
np.sqrt(50)

7.0710678118654755

In [31]:
v = np.array([3, 4, 5])

In [33]:
norm_v = v/np.linalg.norm(v)

In [34]:
norm_v

array([0.42426407, 0.56568542, 0.70710678])

In [37]:
theta = 45  # degrees
np.tan(np.pi*theta/180)

0.9999999999999999

In [ ]:
def render(spheres):
    height = 480
    width = 640
    image = np.zeros((height, width), 3)
    fov = 30 # degrees
    # calculate inverse width, inverse height, aspect ratio, and angle 
    # iterate through each pixel in the image
      # trace the ray from (0,0) to that pixel
      # calculate the color of that pixel
    
    # save the image
    Image.fromarray(image).save("rendered.png")

In [38]:
import imageio

In [42]:
tflogo = np.array(imageio.read("/Users/avilay/projects/bitbucket/learn/learn-scipy/tf-logo.jpg"))

In [43]:
tflogo.shape

()

In [49]:
logo = np.array(imageio.imread("/Users/avilay/projects/bitbucket/learn/learn-scipy/tf-logo.jpg"))

In [50]:
logo.shape

(500, 1000, 3)

In [51]:
logo[0,0]

array([255, 255, 255], dtype=uint8)

In [52]:
logo[250, 500]

array([229,  83,  32], dtype=uint8)

In [53]:
type(logo)

numpy.ndarray

In [54]:
logo[250, 500] = trace(None, None, None, None)

In [55]:
logo[250, 500]

array([1, 0, 0], dtype=uint8)

In [56]:
spheres = []

In [ ]:
spheres.append(s1)
spheres.append(s2)