# Arrays, Vectors, and Matrixes

## Declaration

### Syntax and Types

General syntax seems to be -
  * Commas are used for enumerating elements
  * Spaces are used for stacking elements horizontally
  * Semicolons are used for stacking elements vertically

$\mathcal{Vector}$ are used for 1D *column* vectors. Either commas or semicolons can be used to declare these. If I want to create a *row* vector, I'll have to use spaces. Furthermore I'll end up with a type of $1 \times 2$ $\mathcal{Matrix}$.

$\mathcal{Matrix}$ are used for 2D list of numbers. Here spaces are used for defining a row, and rows are separated (or stacked on top of each other) by semicolons. If I try to seperate a row by commas instead, I'll end up with the outer type being a vector.

$\mathcal{Array}$ are used for multi-dimensional tensors.

It is not possible to define jagged tensors.

### Initialization

##### 1D Column Vector

In [122]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [123]:
u = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

##### 1D row vector of type Matrix

In [124]:
r = [1 2]

1×2 Matrix{Int64}:
 1  2

##### 2D Matrix

In [125]:
A = [
    [1 2 3];
    [4 5 6]
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

##### N-D Tensor of type Array
I could not find any way of doing this using literals. Either I need to use a funciton like `zeros`, `fill`, etc. or use the `Array{T}(undef, dims)` syntax. See [Multi-dimensional Arrays](https://docs.julialang.org/en/v1/manual/arrays/) for a full list of such functions.

`Array{Float32}(undef, (4, 3, 2))` will allocate memory for a $4 \times 3 \times 2$ tensor of 4-byte floats. The `undef` tells Julia to not bother with cleaning up the memory. So the allocated memory might have garbage left by its previous occupants. While these are useful for creating tensors with more than 2 dimensions, I can ofcourse use it for 1- or 2-D lists as well.

In [132]:
X = Array{Float32}(undef, (4, 3, 2))

4×3×2 Array{Float32, 3}:
[:, :, 1] =
 6.0f-45  4.0f-45  1.07919f-30
 0.0      0.0      1.0f-45
 1.1f-44  4.5f-44  1.4f-43
 0.0      0.0      0.0

[:, :, 2] =
 1.401f-42  2.8f-44      4.0f-45
 0.0        0.0          0.0
 3.5f-43    1.50266f-23  4.5f-44
 0.0        1.0f-45      0.0

In [137]:
# Even though I said Array, I still get a matrix because this is 2D. I can also use the `Matrix` type here to get the same result
X = Array{Float32}(undef, (3, 2))

3×2 Matrix{Float32}:
 0.0      0.0
 0.0      0.0
 4.6f-44  0.0

In [138]:
X = Matrix{Float32}(undef, (3, 2))

3×2 Matrix{Float32}:
 0.0      0.0
 0.0      0.0
 4.6f-44  0.0

In [139]:
# Same with Vector
X = Array{Float32}(undef, 2)

2-element Vector{Float32}:
 1.6046382f20
 1.0f-45

##### Proof that `u` and `v` are of type `Vector`

In [75]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [76]:
u = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [77]:
@assert v == u

##### Proof that `u` and `v` are *column* vectors

In [68]:
M = [
    [1 2 3];
    [4 5 6]
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [69]:
M * v

2-element Vector{Int64}:
 14
 32

In [70]:
M * u

2-element Vector{Int64}:
 14
 32

##### Proof that `r` is a row vector with type `Matrix`

In [78]:
r = [1 2]

1×2 Matrix{Int64}:
 1  2

In [79]:
r * M

1×3 Matrix{Int64}:
 9  12  15

In [80]:
r_ = [1, 2]

2-element Vector{Int64}:
 1
 2

In [81]:
r_ * M

LoadError: DimensionMismatch: matrix A has dimensions (2,1), matrix B has dimensions (2,3)

## Indexing

In general I'll need to specify the indexes at all dimensions when indexing into a multidimensional list. Lets look at 2D matrices first. The indexing of multidimenstional tensors can be better understood after reading through the visualization.

$$
M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$$

In numpy `M[1]` is shorthand for `M[1, :]`. In numpy I can think of this as an 2-element array of 3-element arrays, i.e., there is a recursive relationship. But in Julia this is not true, `M[1]` will actually just give me the first element of the unraveled list, i.e., `M[1] = 1`. In order to get the first row, I have to specify all the dimensions - `M[1, :]`.

In [117]:

M = [
    [1 2 3];
    [4 5 6]
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [118]:
M[1]

1

In [119]:
M[1, :]

3-element Vector{Int64}:
 1
 2
 3

## Visualization

### 1D and 2D lists

Lets get the easy ones out of the way first.

Vectors (aka column vectors), are defined as `u = [1, 2]` or `v = [1; 2]` and they can be visualized as follows -
$$
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

Row vectors (aka $1 \times n$ Matrix) are defined as `r = [1 2]` and can be visualized as -
$$
\left[ 1 \; 2 \right]
$$

Matrix (aka 2D lists) defined as -
```
M = [
    [3 5 7];
    [4 6 8]
]
```
and can be visualized as -
$$
\begin{bmatrix}
3 & 5 & 7 \\
4 & 6 & 8 \\
\end{bmatrix}
$$



### Multidimensional Arrays aka Tensors
The way to interpret tensors in Julia is very different than numpy. 

##### Numpy
In numpy a $4 \times 3 \times 2$ tensor is really a $3 \times 2$ matrix arranged in an 4-element array. Note, in numpy an ndarray can behave like row vector when it needs to and a column vector when it needs to.

```python
X = np.arange(1, 25).reshape((4, 3, 2))
```
We can visualize it pretty much the way it is printed -
$$
\left[  
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
4 & 6 \\
\end{bmatrix}
\;
\begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12 \\
\end{bmatrix}
\;
\begin{bmatrix}
13 & 14 \\
15 & 16 \\
17 & 18 \\
\end{bmatrix}
\;
\begin{bmatrix}
19 & 20 \\
21 & 22 \\
23 & 24 \\
\end{bmatrix}
\right]
$$

And the more dimensions we add - it just becomes an array of arrays and so on. So a $5 \times 4 \times 3 \times 2$ is an array of 5 elements where each element is an array of 4 elements, where each element is a $3 \times 2$ matrix.

$$
\left[
\left[  
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
4 & 6 \\
\end{bmatrix}
\;
\begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12 \\
\end{bmatrix}
\;
\begin{bmatrix}
13 & 14 \\
15 & 16 \\
17 & 18 \\
\end{bmatrix}
\;
\begin{bmatrix}
19 & 20 \\
21 & 22 \\
23 & 24 \\
\end{bmatrix}
\right]

\quad

\left[  
\begin{bmatrix}
25 & 26 \\
27 & 28 \\
29 & 30 \\
\end{bmatrix}
\;
\begin{bmatrix}
31 & 32 \\
33 & 34 \\
35 & 36 \\
\end{bmatrix}
\;
\begin{bmatrix}
37 & 38 \\
39 & 40 \\
41 & 42 \\
\end{bmatrix}
\;
\begin{bmatrix}
43 & 44 \\
45 & 46 \\
47 & 48 \\
\end{bmatrix}
\right]
\cdots
\right]
$$

I like to think of this as **inside-out**, where the "main" matrix is defined with the innermost shape, and as we go outside we get arrays.

Accessing the elements works in an intuitive way, where `X[0]` will give me the first element of the outermost 5-element array, and this will be a 4-element array - 
$$
X_0 = \left[  
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
4 & 6 \\
\end{bmatrix}
\;
\begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12 \\
\end{bmatrix}
\;
\begin{bmatrix}
13 & 14 \\
15 & 16 \\
17 & 18 \\
\end{bmatrix}
\;
\begin{bmatrix}
19 & 20 \\
21 & 22 \\
23 & 24 \\
\end{bmatrix}
\right] \\
$$

$$
X_{0,0} = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
4 & 6 \\
\end{bmatrix}
$$

$$
X_{0,0,0} = \left[ 1 \quad 2 \right]
$$
##### Julia
In Julia a $4 \times 3 \times 2$ tensor is a $4 \times 3$ matrix arranged in a list (I don't know whether to interpret is as a row vector or a column vector) of 2-elements. So very much like numpy.

Notice that unlike numpy, the numbers in the range are raveled column-wise. 

```
X = reshape(range(1, 24), (4, 3, 2))
```
Again, this can also be visualized as it is printed (and similar to numpy visualization except for the values) -
$$
\left[
\begin{bmatrix}
1 & 5 & 9 \\
2 & 6 & 10 \\
3 & 7 & 11 \\
4 & 8 & 12 \\
\end{bmatrix}

\;
\begin{bmatrix}
13 & 17 & 21 \\
14 & 18 & 22 \\
15 & 19 & 23 \\
16 & 20 & 24 \\
\end{bmatrix}
\right]
$$

However when the number of dimensions are even e.g., $5 \times 4 \times 3 \times 2$ is actually a bunch of $5 \times 4$ matrices, arranged in a $3 \times 2$ grid.
```
X = reshape(range(1, 120), (5, 4, 3, 2))
```
$$
X = \begin{bmatrix}

\begin{bmatrix}
1 & 6 & 11 & 16 \\
2 & 7 & 12 & 17 \\
3 & 8 & 13 & 18 \\
4 & 9 & 14 & 19 \\
5 & 10 & 15 & 20 \\
\end{bmatrix} 

& \begin{bmatrix}
61 & 66 & 71 & 76 \\
62 & 67 & 72 & 77 \\
63 & 68 & 73 & 78 \\
64 & 69 & 74 & 79 \\
65 & 70 & 75 & 80 \\
\end{bmatrix}

\\

\begin{bmatrix}
21 & 26 & 31 & 36 \\
22 & 27 & 32 & 37 \\
23 & 28 & 33 & 38 \\
24 & 29 & 34 & 39 \\
25 & 30 & 35 & 40 \\
\end{bmatrix}

& \begin{bmatrix}
81 & 86 & 91 & 96 \\
82 & 87 & 92 & 97 \\
83 & 88 & 93 & 98 \\
84 & 89 & 94 & 99 \\
85 & 90 & 95 & 100 \\
\end{bmatrix}

\\

\begin{bmatrix}
41 & 46 & 51 & 56 \\
42 & 47 & 52 & 57 \\
43 & 48 & 53 & 58 \\
44 & 49 & 54 & 59 \\
45 & 50 & 55 & 60 \\
\end{bmatrix}

& \begin{bmatrix}
101 & 106 & 111 & 116 \\
102 & 107 & 112 & 117 \\
103 & 108 & 113 & 118 \\
104 & 109 & 114 & 119 \\
105 & 110 & 115 & 120 \\
\end{bmatrix}

\\
\end{bmatrix}
$$

Looking at this layout I'd think that `X[1]` will give me the first row of this $3 \times 2$ matrix, but that is not the case. In order to get the first row of two matrices, I'll have to givre `X[:, :, 1, :]` because even the indexing works outside-in, where the outermost dimensions specify the innermost matrix, so `:, :` tells Julia I want the entire innermost matrix, and then `1, :` tells it to get first row and all columns. 

In order to get the first matrix (starting with 1) I'd think that `X[1, 1]` will do the trick, but that'll throw an error. I'll need to say `X[:, :, 1, 1]`.

I have this wrong intuition because I am thinking that Julia treats these structures as recursive, i.e., the outermost structure is a $3 \times 2$ matrix with each element being a $5 \times 4$ matrix. But in Julia, this entire thing is a $5 \times 4 \times 3 \times 2$ tensor.In general I'll need to specify the index of each dimension to retrieve anything. The only exception is the first dimension where `X[1] = 1` and `X[2] = 2` and so on. 



In [120]:
dims = (5, 4, 3, 2)
X = reshape(range(1, prod(dims)), dims)

5×4×3×2 reshape(::UnitRange{Int64}, 5, 4, 3, 2) with eltype Int64:
[:, :, 1, 1] =
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

[:, :, 2, 1] =
 21  26  31  36
 22  27  32  37
 23  28  33  38
 24  29  34  39
 25  30  35  40

[:, :, 3, 1] =
 41  46  51  56
 42  47  52  57
 43  48  53  58
 44  49  54  59
 45  50  55  60

[:, :, 1, 2] =
 61  66  71  76
 62  67  72  77
 63  68  73  78
 64  69  74  79
 65  70  75  80

[:, :, 2, 2] =
 81  86  91   96
 82  87  92   97
 83  88  93   98
 84  89  94   99
 85  90  95  100

[:, :, 3, 2] =
 101  106  111  116
 102  107  112  117
 103  108  113  118
 104  109  114  119
 105  110  115  120

In [121]:
X[:, :, 1, :]

5×4×2 Array{Int64, 3}:
[:, :, 1] =
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

[:, :, 2] =
 61  66  71  76
 62  67  72  77
 63  68  73  78
 64  69  74  79
 65  70  75  80

In [97]:
X[1, 1, :]

2-element Vector{Int64}:
  1
 13

Another common way of initializing that I have seen is `Array{Int}(undef, (2, 2))`. This is simply telling the Julia runtime to allocate an array of size `2x2` but don't bother initializing the memory. So the memory location might have some other garbage value left over from its earlier occupants. Of course I can pass any tuple to this constructor, so instead of `(2, 2)` I can create a `(2, 2, 3)` tensor and so forth.

In [57]:
A = Array{Int}(undef, (3, 2))

3×2 Matrix{Int64}:
 4386390024  4704667536
 4386390024  4386390024
 4386390024  4386390024

In [58]:
v = Vector{Int}(undef, 2)

2-element Vector{Int64}:
 4386390640
 4717861552

In [59]:
[2 2]

1×2 Matrix{Int64}:
 2  2

In [60]:
[2, 2]

2-element Vector{Int64}:
 2
 2

In [61]:
[2; 2]

2-element Vector{Int64}:
 2
 2

In [62]:
[2, 2] == [2; 2]

true

In [63]:
[2, 2] == [2 2]

false

In [64]:
[2; 2] == [2 2]

false

In [65]:
M = Matrix{Float32}(undef, (3, 2))

3×2 Matrix{Float32}:
 1.0f-45  0.0
 0.0      0.00388838
 1.0f-45  1.0f-45

If I do want an initialized array then I should use the `fill` function.

## Operations

In general there are two versions of each arithmetic operator `<op>` for the full vectorized form and `.<op>` for element-wise form. But which will give what result is something I still need to develop intution for.

In [143]:
# A column vector and matrix will work with .+ but not with +
A = [
    [1 2 3];
    [4 5 6]
]
v = [7, 8]
A .+ v

2×3 Matrix{Int64}:
  8   9  10
 12  13  14

In [144]:
A + v

LoadError: DimensionMismatch: dimensions must match: a has dims (Base.OneTo(2), Base.OneTo(3)), must have singleton at dim 2

In [145]:
# A row vector and matrix will also work. Julia is able to figure out the rigth thing to do based on dimensions.
u = [7 8 9]
A .+ u

2×3 Matrix{Int64}:
  8  10  12
 11  13  15

In [146]:
A + u

LoadError: DimensionMismatch: dimensions must match: a has dims (Base.OneTo(2), Base.OneTo(3)), b has dims (Base.OneTo(1), Base.OneTo(3)), mismatch at 1

In [148]:
# If B is a matrix with the same shape as A, then both + and .+ will work and they will give the same result
B = [
    [7 8 9];
    [10 11 12]
]
A + B

2×3 Matrix{Int64}:
  8  10  12
 14  16  18

In [149]:
A .+ B

2×3 Matrix{Int64}:
  8  10  12
 14  16  18

In [153]:
# Matrix-Matrix multiplication will work when the dims are (m, n) and (n, p) using the * operator. But .* will not work in this case.
# .* will work with (m, n) and (m, n) matrix.
C = [
    [7 8];
    [9 10];
    [11 12]
]
A * C

2×2 Matrix{Int64}:
  58   64
 139  154

In [154]:
A .* C

LoadError: DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 2 and 3

In [155]:
A .* B

2×3 Matrix{Int64}:
  7  16  27
 40  55  72

Julia has a bunch of other [linalg operators](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/).

  * `'` will give the transpose of a real valued matrix and the Hermitian (conjugate transpose) of a complex matrix.
  * `adjoint` and `'` are equivalent.

In [156]:
A = [
    [1 2 3];
    [4 5 6]
]
A'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

In [157]:
C = [
    [1+0.1im 2+0.2im 3+0.3im];
    [4+0.4im 5+0.5im 6+0.6im]
]
C'

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 1.0-0.1im  4.0-0.4im
 2.0-0.2im  5.0-0.5im
 3.0-0.3im  6.0-0.6im

In [158]:
adjoint(C)

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 1.0-0.1im  4.0-0.4im
 2.0-0.2im  5.0-0.5im
 3.0-0.3im  6.0-0.6im

In [159]:
adjoint(A)

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6