In [7]:
import numpy as np
import functools as fun

In [4]:
rng = np.random.default_rng(1)

In [3]:
[rng.random() for _ in range(5)]

[0.5118216247002567,
 0.9504636963259353,
 0.14415961271963373,
 0.9486494471372439,
 0.31183145201048545]

In [5]:
A = np.array([
    [0.392019, 0.517252, 0.070731],
    [0.544392, 0.602742, 0.863450]
])

B = np.array([
    [0.012466, 0.904164],
    [0.118664, 0.081877],
    [0.779691, 0.280069],
])
C = A @ B
C

array([[0.12141442, 0.41661007],
       [0.75153436, 0.78339593]])

In [9]:
rng.random((2, 3))

array([[0.75351311, 0.53814331, 0.32973172],
       [0.7884287 , 0.30319483, 0.45349789]])

In [8]:
fun.reduce(lambda acc, x: acc*x, (2, 3, 4), 1)

24

In [25]:
dims = (5, 4, 3, 2)
X = np.arange(1, np.prod(dims)+1).reshape(dims)
X

array([[[[  1,   2],
         [  3,   4],
         [  5,   6]],

        [[  7,   8],
         [  9,  10],
         [ 11,  12]],

        [[ 13,  14],
         [ 15,  16],
         [ 17,  18]],

        [[ 19,  20],
         [ 21,  22],
         [ 23,  24]]],


       [[[ 25,  26],
         [ 27,  28],
         [ 29,  30]],

        [[ 31,  32],
         [ 33,  34],
         [ 35,  36]],

        [[ 37,  38],
         [ 39,  40],
         [ 41,  42]],

        [[ 43,  44],
         [ 45,  46],
         [ 47,  48]]],


       [[[ 49,  50],
         [ 51,  52],
         [ 53,  54]],

        [[ 55,  56],
         [ 57,  58],
         [ 59,  60]],

        [[ 61,  62],
         [ 63,  64],
         [ 65,  66]],

        [[ 67,  68],
         [ 69,  70],
         [ 71,  72]]],


       [[[ 73,  74],
         [ 75,  76],
         [ 77,  78]],

        [[ 79,  80],
         [ 81,  82],
         [ 83,  84]],

        [[ 85,  86],
         [ 87,  88],
         [ 89,  90]],

        [[ 91,  92]

In [30]:
X[0]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [31]:
X[0, 0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
X[0, 0, 0]

array([1, 2])

In [33]:
A = np.array([
    [3, 5, 7],
    [4, 6, 8]
])

In [34]:
A[0]

array([3, 5, 7])

In [35]:
A[0, :]

array([3, 5, 7])

In [23]:
# r is interpreted as a row vector
r = np.array([1, 2])
print(type(r), r.shape)
r @ A

<class 'numpy.ndarray'> (2,)


array([11, 17, 23])

In [24]:
# v is interpreted as a column vector
v = np.array([1, 2, 3])
print(type(v), v.shape)
A @ v

<class 'numpy.ndarray'> (3,)


array([34, 40])

In [37]:
int("A")

ValueError: invalid literal for int() with base 10: 'A'

In [38]:
ord("A")

65

In [39]:
ord("a")

97

In [44]:
hex(65)

'0x41'

In [42]:
bin(0x41)

'0b1000001'

In [43]:
int(0x41)

65