In [15]:
import gym
import numpy as np

In [16]:
np.set_printoptions(precision=3)

In [9]:
env = gym.make("CartPole-v1")

In [11]:
env.observation_space

Box(4,)

In [12]:
env.action_space

Discrete(2)

In [13]:
s = env.reset()

In [38]:
s = env.reset()
buffer = []
done = False
while not done:
    a = env.action_space.sample()
    s_, r, done, _ = env.step(a)
    buffer.append((s, a, r, s_, done))

In [39]:
buffer

[(array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.001,  0.161,  0.008, -0.29 ]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  0,
  1.0,
  array([ 0.004, -0.035,  0.002,  0.005]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.003,  0.16 ,  0.003, -0.287]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  0,
  1.0,
  array([ 0.007, -0.035, -0.003,  0.006]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.006,  0.161, -0.003, -0.287]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  0,
  1.0,
  array([ 0.009, -0.035, -0.009,  0.004]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.008,  0.161, -0.009, -0.291]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.012,  0.356, -0.015, -0.587]),
  False),
 (array([ 0.002, -0.034,  0.008, -0.   ]),
  1,
  1.0,
  array([ 0.019,  0.551, -0.026, -0.884]),
  False),
 (array([ 0.002, -0.034,  0.

In [8]:

s_, r, done

(0, 0.0, False)